// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: types/cloud.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If set, prioritize over active region.
	ActiveZone string `protobuf:"bytes,1,opt,name=active_zone,json=activeZone,proto3" json:"active_zone,omitempty"`
	// Valid only when active zone is not set.
	ActiveRegion string `protobuf:"bytes,2,opt,name=active_region,json=activeRegion,proto3" json:"active_region,omitempty"`
	// If set, prioritize over passive region.
	PassiveZone string `protobuf:"bytes,3,opt,name=passive_zone,json=passiveZone,proto3" json:"passive_zone,omitempty"`
	// Valid only when passive zone is not set.
	PassiveRegion string `protobuf:"bytes,4,opt,name=passive_region,json=passiveRegion,proto3" json:"passive_region,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_cloud_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetActiveZone() string {
	if x != nil {
		return x.ActiveZone
	}
	return ""
}

func (x *Location) GetActiveRegion() string {
	if x != nil {
		return x.ActiveRegion
	}
	return ""
}

func (x *Location) GetPassiveZone() string {
	if x != nil {
		return x.PassiveZone
	}
	return ""
}

func (x *Location) GetPassiveRegion() string {
	if x != nil {
		return x.PassiveRegion
	}
	return ""
}

type GCPInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceAccount []byte    `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	Location       *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GCPInfo) Reset() {
	*x = GCPInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_cloud_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPInfo) ProtoMessage() {}

func (x *GCPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPInfo.ProtoReflect.Descriptor instead.
func (*GCPInfo) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{1}
}

func (x *GCPInfo) GetServiceAccount() []byte {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *GCPInfo) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type AWSInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Prioritized over id/secret.
	RoleArn      string    `protobuf:"bytes,1,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	ClientIdArn  string    `protobuf:"bytes,2,opt,name=client_id_arn,json=clientIdArn,proto3" json:"client_id_arn,omitempty"`
	ClientSecret string    `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Location     *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *AWSInfo) Reset() {
	*x = AWSInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_cloud_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AWSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSInfo) ProtoMessage() {}

func (x *AWSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSInfo.ProtoReflect.Descriptor instead.
func (*AWSInfo) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{2}
}

func (x *AWSInfo) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *AWSInfo) GetClientIdArn() string {
	if x != nil {
		return x.ClientIdArn
	}
	return ""
}

func (x *AWSInfo) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AWSInfo) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type AzureInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AzureInfo) Reset() {
	*x = AzureInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_cloud_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureInfo) ProtoMessage() {}

func (x *AzureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureInfo.ProtoReflect.Descriptor instead.
func (*AzureInfo) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{3}
}

var File_types_cloud_proto protoreflect.FileDescriptor

var file_types_cloud_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x76, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x7a, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x73,
	0x73, 0x69, 0x76, 0x65, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x07, 0x47, 0x43, 0x50, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x6f, 0x72, 0x74,
	0x65, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xa6, 0x01, 0x0a, 0x07, 0x41, 0x57, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x41, 0x72, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x41, 0x72, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x37, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x7a, 0x75,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x62, 0x6c, 0x75, 0x65, 0x2d, 0x69,
	0x6f, 0x2f, 0x76, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x2d, 0x67, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_cloud_proto_rawDescOnce sync.Once
	file_types_cloud_proto_rawDescData = file_types_cloud_proto_rawDesc
)

func file_types_cloud_proto_rawDescGZIP() []byte {
	file_types_cloud_proto_rawDescOnce.Do(func() {
		file_types_cloud_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_cloud_proto_rawDescData)
	})
	return file_types_cloud_proto_rawDescData
}

var file_types_cloud_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_cloud_proto_goTypes = []any{
	(*Location)(nil),  // 0: vortexproto.types.Location
	(*GCPInfo)(nil),   // 1: vortexproto.types.GCPInfo
	(*AWSInfo)(nil),   // 2: vortexproto.types.AWSInfo
	(*AzureInfo)(nil), // 3: vortexproto.types.AzureInfo
}
var file_types_cloud_proto_depIdxs = []int32{
	0, // 0: vortexproto.types.GCPInfo.location:type_name -> vortexproto.types.Location
	0, // 1: vortexproto.types.AWSInfo.location:type_name -> vortexproto.types.Location
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_cloud_proto_init() }
func file_types_cloud_proto_init() {
	if File_types_cloud_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_cloud_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_cloud_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GCPInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_cloud_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AWSInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_cloud_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AzureInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_cloud_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_cloud_proto_goTypes,
		DependencyIndexes: file_types_cloud_proto_depIdxs,
		MessageInfos:      file_types_cloud_proto_msgTypes,
	}.Build()
	File_types_cloud_proto = out.File
	file_types_cloud_proto_rawDesc = nil
	file_types_cloud_proto_goTypes = nil
	file_types_cloud_proto_depIdxs = nil
}
