// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: vortex/v1/vortex.proto

package vortex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Vortex_Do_FullMethodName = "/vortexproto.vortex.v1.Vortex/Do"
)

// VortexClient is the client API for Vortex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Vortex service definition.
type VortexClient interface {
	// Testing endpoint.
	Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error)
}

type vortexClient struct {
	cc grpc.ClientConnInterface
}

func NewVortexClient(cc grpc.ClientConnInterface) VortexClient {
	return &vortexClient{cc}
}

func (c *vortexClient) Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoResponse)
	err := c.cc.Invoke(ctx, Vortex_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VortexServer is the server API for Vortex service.
// All implementations must embed UnimplementedVortexServer
// for forward compatibility
//
// Vortex service definition.
type VortexServer interface {
	// Testing endpoint.
	Do(context.Context, *DoRequest) (*DoResponse, error)
	mustEmbedUnimplementedVortexServer()
}

// UnimplementedVortexServer must be embedded to have forward compatible implementations.
type UnimplementedVortexServer struct {
}

func (UnimplementedVortexServer) Do(context.Context, *DoRequest) (*DoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedVortexServer) mustEmbedUnimplementedVortexServer() {}

// UnsafeVortexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VortexServer will
// result in compilation errors.
type UnsafeVortexServer interface {
	mustEmbedUnimplementedVortexServer()
}

func RegisterVortexServer(s grpc.ServiceRegistrar, srv VortexServer) {
	s.RegisterService(&Vortex_ServiceDesc, srv)
}

func _Vortex_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VortexServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vortex_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VortexServer).Do(ctx, req.(*DoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vortex_ServiceDesc is the grpc.ServiceDesc for Vortex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vortex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vortexproto.vortex.v1.Vortex",
	HandlerType: (*VortexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Vortex_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vortex/v1/vortex.proto",
}
